const customers = [
  {
    id: 1,
    name: "Sarah Johnson",
    age: 32,
    from: "Pennsauken, New Jersey",
    area: "South Jersey, near Philadelphia",
    occupation: "Elementary School Teacher",
    family: "Married with 2 kids",
    pet: "A golden retriever named Buddy",
    service: "Spa Pedicure",
    color: "Light Pink",
    shape: "Oval",
    drink: "Tea",
    personality: "Friendly and talkative",
    image: "👩",
    facts: [
      { question: "What is the customer's name?", answer: "Sarah Johnson", choices: ["Sarah Johnson", "Emily Davis", "Jessica Brown", "Amanda White"] },
      { question: "Where is the customer from?", answer: "Pennsauken, New Jersey", choices: ["Pennsauken, New Jersey", "Camden, New Jersey", "Cherry Hill, New Jersey", "Trenton, New Jersey"] },
      { question: "What area is she from?", answer: "South Jersey, near Philadelphia", choices: ["North Jersey, near New York", "South Jersey, near Philadelphia", "Central Jersey, near Princeton", "Shore area, near Atlantic City"] },
      { question: "What does she do for work?", answer: "Elementary School Teacher", choices: ["Elementary School Teacher", "Nurse", "Office Worker", "Chef"] },
      { question: "Does she have any pets?", answer: "A golden retriever named Buddy", choices: ["A golden retriever named Buddy", "A cat named Mimi", "No pets", "Two dogs named Coco and Milo"] },
      { question: "What service does she want?", answer: "Spa Pedicure", choices: ["Spa Pedicure", "Basic Manicure", "Gel Manicure", "Deluxe Pedicure"] },
      { question: "What color does she want?", answer: "Light Pink", choices: ["Light Pink", "Dark Red", "Nude", "Purple"] },
      { question: "What nail shape does she want?", answer: "Oval", choices: ["Oval", "Square", "Round", "Stiletto"] },
      { question: "What drink would she like?", answer: "Tea", choices: ["Tea", "Water", "Juice", "Wine"] }
    ]
  },
  {
    id: 2,
    name: "Maria Rodriguez",
    age: 28,
    from: "Camden, New Jersey",
    area: "South Jersey, near Philadelphia",
    occupation: "Nurse at Cooper Hospital",
    family: "Single, lives with her sister",
    pet: "Two cats named Luna and Star",
    service: "Gel Manicure",
    color: "Dark Red",
    shape: "Square",
    drink: "Water",
    personality: "Busy but friendly",
    image: "👩‍⚕️",
    facts: [
      { question: "What is the customer's name?", answer: "Maria Rodriguez", choices: ["Maria Rodriguez", "Sofia Martinez", "Isabella Garcia", "Valentina Lopez"] },
      { question: "Where is the customer from?", answer: "Camden, New Jersey", choices: ["Camden, New Jersey", "Pennsauken, New Jersey", "Moorestown, New Jersey", "Haddon Township, New Jersey"] },
      { question: "What area is she from?", answer: "South Jersey, near Philadelphia", choices: ["North Jersey, near New York", "South Jersey, near Philadelphia", "Central Jersey, near Princeton", "Shore area, near Atlantic City"] },
      { question: "What does she do for work?", answer: "Nurse at Cooper Hospital", choices: ["Nurse at Cooper Hospital", "Doctor at Jefferson Hospital", "Teacher at Camden School", "Manager at a restaurant"] },
      { question: "Does she have any pets?", answer: "Two cats named Luna and Star", choices: ["Two cats named Luna and Star", "A dog named Max", "No pets", "A bird named Tweety"] },
      { question: "What service does she want?", answer: "Gel Manicure", choices: ["Gel Manicure", "Spa Pedicure", "Acrylic Nails", "Basic Pedicure"] },
      { question: "What color does she want?", answer: "Dark Red", choices: ["Dark Red", "Light Pink", "Black", "Coral"] },
      { question: "What nail shape does she want?", answer: "Square", choices: ["Square", "Oval", "Almond", "Coffin"] },
      { question: "What drink would she like?", answer: "Water", choices: ["Water", "Tea", "Coffee", "Wine"] }
    ]
  },
  {
    id: 3,
    name: "Jennifer Kim",
    age: 45,
    from: "Cherry Hill, New Jersey",
    area: "South Jersey, near Philadelphia",
    occupation: "Small Business Owner",
    family: "Married with 3 kids and a grandchild",
    pet: "A small poodle named Coco",
    service: "Deluxe Pedicure",
    color: "Nude / Beige",
    shape: "Round",
    drink: "Wine",
    personality: "Elegant and sophisticated",
    image: "👩‍💼",
    facts: [
      { question: "What is the customer's name?", answer: "Jennifer Kim", choices: ["Jennifer Kim", "Susan Park", "Michelle Lee", "Christine Cho"] },
      { question: "Where is the customer from?", answer: "Cherry Hill, New Jersey", choices: ["Cherry Hill, New Jersey", "Voorhees, New Jersey", "Marlton, New Jersey", "Medford, New Jersey"] },
      { question: "What area is she from?", answer: "South Jersey, near Philadelphia", choices: ["North Jersey, near New York", "South Jersey, near Philadelphia", "Central Jersey, near Princeton", "Shore area, near Atlantic City"] },
      { question: "What does she do for work?", answer: "Small Business Owner", choices: ["Small Business Owner", "Lawyer", "Doctor", "Real Estate Agent"] },
      { question: "Does she have any pets?", answer: "A small poodle named Coco", choices: ["A small poodle named Coco", "Two golden retrievers", "No pets", "A cat named Princess"] },
      { question: "What service does she want?", answer: "Deluxe Pedicure", choices: ["Deluxe Pedicure", "Gel Manicure", "Spa Pedicure", "Acrylic Nails"] },
      { question: "What color does she want?", answer: "Nude / Beige", choices: ["Nude / Beige", "Hot Pink", "Dark Purple", "Glitter"] },
      { question: "What nail shape does she want?", answer: "Round", choices: ["Round", "Stiletto", "Coffin", "Square"] },
      { question: "What drink would she like?", answer: "Wine", choices: ["Wine", "Tea", "Water", "Juice"] }
    ]
  },
  {
    id: 4,
    name: "Ashley Thompson",
    age: 22,
    from: "Merchantville, New Jersey",
    area: "South Jersey, near Philadelphia",
    occupation: "College Student at Rutgers",
    family: "Single, lives with parents",
    pet: "No pets",
    service: "Acrylic Nails with Nail Art",
    color: "Purple with Glitter",
    shape: "Coffin / Ballerina",
    drink: "Juice",
    personality: "Fun and creative",
    image: "👩‍🎓",
    facts: [
      { question: "What is the customer's name?", answer: "Ashley Thompson", choices: ["Ashley Thompson", "Brittany Wilson", "Kayla Moore", "Taylor Anderson"] },
      { question: "Where is the customer from?", answer: "Merchantville, New Jersey", choices: ["Merchantville, New Jersey", "Collingswood, New Jersey", "Bellmawr, New Jersey", "Runnemede, New Jersey"] },
      { question: "What area is she from?", answer: "South Jersey, near Philadelphia", choices: ["North Jersey, near New York", "South Jersey, near Philadelphia", "Central Jersey, near Princeton", "Shore area, near Atlantic City"] },
      { question: "What does she do?", answer: "College Student at Rutgers", choices: ["College Student at Rutgers", "High School Student", "Works at a mall", "Graphic Designer"] },
      { question: "Does she have any pets?", answer: "No pets", choices: ["No pets", "A hamster named Peanut", "Two cats", "A dog named Rex"] },
      { question: "What service does she want?", answer: "Acrylic Nails with Nail Art", choices: ["Acrylic Nails with Nail Art", "Basic Manicure", "Gel Manicure", "Spa Pedicure"] },
      { question: "What color does she want?", answer: "Purple with Glitter", choices: ["Purple with Glitter", "Plain White", "Nude Pink", "Dark Blue"] },
      { question: "What nail shape does she want?", answer: "Coffin / Ballerina", choices: ["Coffin / Ballerina", "Round", "Square", "Oval"] },
      { question: "What drink would she like?", answer: "Juice", choices: ["Juice", "Water", "Tea", "Coke"] }
    ]
  },
  {
    id: 5,
    name: "Barbara Williams",
    age: 58,
    from: "Haddon Township, New Jersey",
    area: "South Jersey, near Philadelphia",
    occupation: "Retired School Principal",
    family: "Widowed, has 2 adult children and 4 grandchildren",
    pet: "A bird named Sunny",
    service: "Basic Manicure and Pedicure",
    color: "Classic Red",
    shape: "Short and Round",
    drink: "Tea with honey",
    personality: "Warm and motherly",
    image: "👵",
    facts: [
      { question: "What is the customer's name?", answer: "Barbara Williams", choices: ["Barbara Williams", "Patricia Davis", "Nancy Miller", "Linda Wilson"] },
      { question: "Where is the customer from?", answer: "Haddon Township, New Jersey", choices: ["Haddon Township, New Jersey", "Haddonfield, New Jersey", "Audubon, New Jersey", "Oaklyn, New Jersey"] },
      { question: "What area is she from?", answer: "South Jersey, near Philadelphia", choices: ["North Jersey, near New York", "South Jersey, near Philadelphia", "Central Jersey, near Princeton", "Shore area, near Atlantic City"] },
      { question: "What did she do for work?", answer: "Retired School Principal", choices: ["Retired School Principal", "Retired Nurse", "Retired Police Officer", "Retired Librarian"] },
      { question: "Does she have any pets?", answer: "A bird named Sunny", choices: ["A bird named Sunny", "No pets", "Three cats", "A dog named Charlie"] },
      { question: "What service does she want?", answer: "Basic Manicure and Pedicure", choices: ["Basic Manicure and Pedicure", "Deluxe Pedicure", "Gel Manicure", "Acrylic Nails"] },
      { question: "What color does she want?", answer: "Classic Red", choices: ["Classic Red", "Nude", "Light Pink", "Orange"] },
      { question: "What nail shape does she want?", answer: "Short and Round", choices: ["Short and Round", "Long Coffin", "Oval", "Square"] },
      { question: "What drink would she like?", answer: "Tea with honey", choices: ["Tea with honey", "Black coffee", "Cold water", "Orange juice"] }
    ]
  }
];